general {
    lock_cmd = noctalia-shell ipc call lockScreen lock
    before_sleep_cmd = loginctl lock-session
    ignore_dbus_inhibit = false
}

listener {
    timeout = 600
    on-timeout = noctalia-shell ipc call lockScreen lock
}

listener {
    timeout = 3600
    on-timeout = noctalia-shell ipc call sessionMenu lockAndSuspend
}
